moviemagic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('movies.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path

from movies import views

app_name='movies'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # ex: /movies/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),


]

movies/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=200)
    title_type = models.CharField(max_length=200)
    release_year = models.CharField(max_length=20)
    user_rating = models.FloatField(default=5, validators=[MaxValueValidator(10),
                                                             MinValueValidator(0)],)
    vote_count = models.IntegerField(default=1000, validators=[MinValueValidator(100)])

    def __str__(self):
        return '{}, {}, {}'.format(self.title, self.release_year, self.user_rating)


class Genre(models.Model):
    """
    Since one movie can have multiple genres, this can be expressed as
    one-to-many relationship between movie and genre
    """
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    genre = models.CharField(max_length=100)

    def __repr__(self):
        return '{}'.format(self.genre)

    # def __str__(self):
    #     return '{}'.format(self.genre)

movies/forms.py
from django import forms


class SearchForm(forms.Form):
    user_rating_min = forms.CharField(label='Minimal user rating')

movies/views.py
from django.views import generic
from .models import Movie
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import SearchForm


# List view displays a list of objects (i.e. Movies)
class IndexView(generic.ListView):
    # List view needs a context to be provided explicitly, otherwise a
    context_object_name = 'latest_movies'
    template_name = 'movies/index.html'

    def get_queryset(self):
        return Movie.objects.order_by('title')


# Detail view displays a details of a Movie object
class DetailView(generic.DeleteView):
    # For DetailView the question variable is provided automatically – since we’re using a Django model(Question),
    # Django is able to determine an appropriate name for the context variable.
    # Also the DetailView generic view expects the primary key value captured from the URL to be called "pk",
    # so we’ve changed question_id to pk for the generic views in polls/urls.py
    model = Movie
    template_name = 'movies/detail.html'


abc = 'THIS IS SOME SHIT GOING ON!'


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchForm()

    return render(request, 'movies/movie.html', {'form': form})

movies/templates/movies/detail.html
<h1>{{ movie.title }}</h1>
<p>{{ movie.release_year }}</p>
<ul>
{% for g in movie.genre_set.all %}
    <div>{{ g.genre }}</div>
{% endfor %}
</ul>

{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'movies/style.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'result' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

movies/templates/movies/index.html
{% if latest_movies %}
    <ul>
    {% for movie in latest_movies %}
{#        <li><a href="/movies/{{ movie.id }}/">{{ movie.title}}</a></li>#}
        <li><a href="{% url 'movies:detail' movie.id %}">{{ movie.title}}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>Aww snap, no movies available :/</p>
{% endif %}

movies/templates/movies/movie.html
<form action="movie.html" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>